excerpt_separator: ""
pygments: true
markdown: kramdown
title: dev.ropater
tagline: 
description: blogsite via <a href="https://tinypress.co/&quot; target=&quot;_blank">Tinypress</a>
paginate: 5
